name: alert_info
description: "Alert info is flutter package to display an animated alert info, warning, succes or error message from the top or bottom"
version: 0.0.3
homepage: https://github.com/MoezAyadiDev/alert_info
repository: https://github.com/MoezAyadiDev/alert_info
screenshots:
  - description: "Screenshot for different type of alert info"
    path: example/assets/screenshots/alert_info_image.png
topics:
  - snackbar
  - toast
  - message
  - alert

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
